# Generated by Django 3.1.1 on 2020-09-28 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectManager',
            new_name='Project',
        ),
    ]
